prplmesh: refactor prplmesh init.d script
Cleanup of the all UCI configuration. UCI is not
used anymore.

Configuration was completelly moved to datamodel:

 * ManagementMode
 * CertificationMode

References: FEAT-26

Closes: PPM-3335

Signed-off-by: Volodymyr Pavlenko <v.pavlenko@inango-systems.com>
Signed-off-by: Petr Štetiar <petr.stetiar@prplfoundation.org>

diff --git a/services/prplmesh/files/etc/init.d/prplmesh b/services/prplmesh/files/etc/init.d/prplmesh
--- a/services/prplmesh/files/etc/init.d/prplmesh
+++ b/services/prplmesh/files/etc/init.d/prplmesh
@@ -1,233 +1,296 @@
 #!/bin/sh /etc/rc.common
 
-. /lib/functions/system.sh
-
 START=99
 NAME=prplmesh
 
-#####################################
-# Helper functions for wlan ready
-#####################################
+AGENT_DM_CACHE_FILE_PATH=/opt/prplmesh/share/agent/odl/agent.odl
+AGENT_DM_DEFAULTS_FILE_PATH=/opt/prplmesh/config/agent/odl/defaults.d/00_slave_configuration.odl
 
-hostapd_ready()
-{
-        hostapd_cli -i$1 stat &>/dev/null || ba-cli Device.WiFi.Radio.?0 &> /dev/null
+##############################
+# Log function - log_msg
+# Usage: log_msg "message"
+##############################
+log_msg() {
+    # Logs to syslog and echoes to stdout
+    local saved_exit_code=$?  
+    logger -t "${NAME}" "$1"
+    echo "$1"
+    return $saved_exit_code  
 }
 
-wlan_reset()
-{
-        wifi down
-        sleep 5
-        local leftover_processes="$(ps | grep '[h]ostapd\|[s]upp')"
-        if [ -n "$leftover_processes" ]; then
-                logger -t "${NAME}" -p daemon.warn "Wlan procceses still running after wifi down: $leftover_processes"
-                echo "Wlan procceses still running after wifi down: $leftover_processes"
-                # STA interfaces/processes sometimes not closed properly (https://jira.prplfoundation.org/browse/PPM-1778)
-                # This issue was spotted after wifi driver release update UGW8.5.2 in prplos.
-                # Currently just log this event and continue.
-                # In case wlan will not recover wlan_ready() will handle it.
-        fi   
-        wifi up
+###########################################
+# 1. Helper functions - Wi-Fi Operations
+###########################################
+
+__wlan_reset__() {
+    wifi down
+    sleep 5
+    local leftover_processes="$(ps | grep '[h]ostapd\|[s]upp')"
+    if [ -n "$leftover_processes" ]; then
+        log_msg "Wlan processes still running after wifi down: $leftover_processes"
+        # STA interfaces/processes sometimes not closed properly (https://jira.prplfoundation.org/browse/PPM-1778)
+        # This issue was spotted after wifi driver release update UGW8.5.2 in prplos.
+        # Currently just log this event and continue.
+        # In case wlan will not recover wlan_ready() will handle it.
+    fi
+    wifi up
 }
 
-wlan_ready()
-{
-        for iface; do
-                if ! hostapd_ready "$iface"; then
-                        logger -t "${NAME}" -p daemon.warn "$0: wlan $iface not ready"
-                        return 1
-                fi
-        done
+# Function __dm_obj_exists__ <obj_path>
+#
+# returns true if obj is found in ba-cli
+# returns false if otherwise
+#
+# usage __dm_obj_exists__ "Device.WiFi.Radio"
+__dm_obj_exists__() {
+    local obj_path=$1
+    ba-cli "${obj_path}.?0" | grep -Eq "No data found|ERROR" &>/dev/null && return 1
+    return 0
 }
 
-get_hostap_iface() 
-{
-        local radio="$1"
-        uci get "prplmesh.$radio.hostap_iface"
+__check_wlan_available__() {
+    # This check is kept like it was without any changes. It is very specific and works like this:
+    # 1. hostapd_cli - checks if hostapd daemon responsible for managing AP 
+    #        on $1 iface is running at the moment 
+    #        (usually it fails if no WiFi.AccessPoint.*.Enable=1 are set)
+    # 2. ba-cli - checks for 'Radio.?0', but actually it ALWAYS return 0 exit code. 
+    #        But more interesting is that under the hood it has 'wait' for pWHM ready, 
+    #        so it helps us to start prplmesh in time without breaking the boot sequence 
+    # 3. So, if hostapd is not running, we do the check for Radio object, that just waits
+    #        for pWHM ready and start prplmesh, saying that "WLAN is ready", tho it's not
+    hostapd_cli -i$1 stat &>/dev/null || ba-cli Device.WiFi.Radio.?0 &> /dev/null
 }
 
-wlan_ready_poll()
-{
-        local delay=${1-3}
-        local timeout=60
-
-        # load the prplmesh config to be able to get the radio iface:
-        config_load prplmesh
-        ifaces="$(config_foreach get_hostap_iface wifi-device)"
-
-        start_time="$(date -u +%s)"
-        while true ; do
-                if wlan_ready $ifaces; then
-                        break
-                fi
-
-                end_time="$(date -u +%s)"
-                elapsed="$(($end_time-$start_time))"
-                if [ "$elapsed" -gt "$timeout" ]; then
-                        return 1
-                fi
-
-                sleep $delay
-        done
+__get_radio_names__() {
+    ba-cli -l "WiFi.Radio.*.Name?"
 }
 
-show_wireless_radio_disabled() 
-{
-        local radio="$1"
-        config_get disabled $radio disabled
-        if [ "$disabled" -eq 0 ]; then
-                echo "$radio is enabled"
-        else
-                echo "$radio is disabled!"
+__all_wlan_ready__() {
+    for iface in "$(__get_radio_names__)"; do
+        if ! __check_wlan_available__ "$iface"; then
+            log_msg "$0: $iface not ready"
+            log_msg "TEMP: $iface not ready"
+            return 1
         fi
+    done
+    return 0
 }
 
-####################
-# main
-####################
+__wait_for_all_wlan_ready__() {
+    local delay=${1-3}
+    local timeout=60
 
-status_function() {
-        # load the wireless config and show the disabled value of each radio
-        config_load wireless
-        config_foreach show_wireless_radio_disabled wifi-device
-
-        echo "enable: $(uci get prplmesh.config.enable)"
-        echo "management_mode: $(uci get prplmesh.config.management_mode)"
-        echo "operating_mode: $(uci get prplmesh.config.operating_mode)"
-        wlan_ready && echo "WLAN Ready" || echo "WLAN not ready"
-        /opt/prplmesh/scripts/prplmesh_utils.sh status
-}
-
-start_function() {
-        if [ $(uci -q get prplmesh.config.enable) == "1" ]; then
-                wlan_ready_poll || {
-                        logger -t "${NAME}" -p daemon.warn "Timeout waiting for WLAN ready!"
-                        exit 1
-                }
-                if [ "$(uci get prplmesh.config.operating_mode)" = "Gateway" ]; then
-                        logger -t "${NAME}" -p daemon.info "Start prplMesh controller & agent"
-                        /opt/prplmesh/scripts/prplmesh_utils.sh start
-                else
-                        logger -t "${NAME}" -p daemon.info "Start prplMesh agent"
-                        /opt/prplmesh/scripts/prplmesh_utils.sh start -m A
-                fi
-        else
-                logger -t "${NAME}" -p daemon.warn "prplMesh is disabled (prplmesh.config.enable=0), skipping..."
-                exit 0
+    start_time="$(date -u +%s)"
+    while true; do
+        if __all_wlan_ready__; then
+            break
         fi
-}
 
-stop_function() {
-        logger -t "${NAME}" -p daemon.info "Stop prplMesh"
-        /opt/prplmesh/scripts/prplmesh_utils.sh stop
-        # since prplmesh changes the wifi runtime configuration,
-        # restart wifi when stopping prplmesh
-        # unless using prplmesh wireless hardware manager
-        ubus call WiFi.Radio _get '{"depth":"0"}' &> /dev/null || wlan_reset
-}
-
-enable_function() {
-        logger -t "${NAME}" -p daemon.info "Enable prplMesh (reboot required)"
-        uci set prplmesh.config.enable=1
-        uci commit prplmesh
-}
-
-disable_function() {
-        logger -t "${NAME}" -p daemon.info "Disable prplMesh (reboot required)"
-        uci set prplmesh.config.enable=0
-        uci commit prplmesh
-}
-
-start() {
-        start_function
-}
-
-stop() {
-        stop_function
-}
-
-restart() {
-        if [ $(uci -q get prplmesh.config.enable) == "1" ]; then
-                wlan_ready_poll || {
-                        logger -t "${NAME}" -p daemon.warn "Timeout waiting for WLAN ready!"
-                        exit 1
-                }
-                if [ "$(uci get prplmesh.config.operating_mode)" = "Gateway" ]; then
-                        logger -t "${NAME}" -p daemon.info "Restart prplMesh controller & agent"
-                        /opt/prplmesh/scripts/prplmesh_utils.sh restart
-                else
-                        logger -t "${NAME}" -p daemon.info "Restart prplMesh agent"
-                        /opt/prplmesh/scripts/prplmesh_utils.sh restart -m A
-                fi
-        else
-                logger -t "${NAME}" -p daemon.warn "prplMesh is disabled (prplmesh.config.enable=0), skipping..."
-                exit 0
+        end_time="$(date -u +%s)"
+        elapsed="$(($end_time - $start_time))"
+        if [ "$elapsed" -gt "$timeout" ]; then
+            return 1
         fi
+
+        sleep $delay
+    done
+    return 0
 }
 
-status() {
-        status_function
+###############################################
+# 2. Configuration Service functions
+###############################################
+
+__get_management_mode__() {
+    local management_mode
+
+    if  __dm_obj_exists__ "X_PRPLWARE-COM_Agent.Configuration"; then
+        management_mode="$(ba-cli X_PRPLWARE-COM_Agent.Configuration.ManagementMode? 2>/dev/null | awk -F'= ' '/ManagementMode/ {gsub(/[";]/,"",$2); print $2}')"
+    elif [ -f "${AGENT_DM_CACHE_FILE_PATH}" ]; then
+        # Read from cache ODL file
+        management_mode="$(awk -F'= ' '/parameter .ManagementMode./ {gsub(/[";]/,"",$2); print $2}' "$AGENT_DM_CACHE_FILE_PATH")"
+    else
+        # Read from defaults ODL file
+        management_mode="$(awk -F'= ' '/parameter .ManagementMode./ {gsub(/[";]/,"",$2); print $2}' "$AGENT_DM_DEFAULTS_FILE_PATH")"
+    fi
+
+    echo "$management_mode"
 }
 
-__uci_set_repeater_mode__() {
-        mode=${1-wired}
-        uci set prplmesh.config.management_mode='Multi-AP-Agent'
-        uci set prplmesh.config.operating_mode='WDS-Repeater'
-        if [ "$mode" = "wireless" ]; then
-                uci set prplmesh.config.wired_backhaul=0
+# Function: __sed_config_option_in_odl__ key value file
+#
+# Updates or inserts a configuration parameter in an ODL file.
+#
+# - If the parameter 'key' exists in the specified 'file',
+#   its value is updated to 'value'.
+# - If the parameter does not exist, a new parameter line is
+#   inserted into the 'object Configuration' section of the file.
+#
+# Usage: __sed_config_option_in_odl__ <key> <value> <file>
+__sed_config_option_in_odl__() {
+    local key="$1"
+    local value="$2"
+    local file="$3"
+    local param_line="parameter '${key}' = \"${value}\";"
+
+    # Check if the parameter exists
+    if grep -q "parameter '${key}'" "$file"; then
+        # Update the existing parameter value
+        sed -i "s|^\([[:space:]]*parameter '${key}' = \).*;|\1\"${value}\";|" "$file"
+    else
+        # Insert new parameter inside object 'Configuration' { ... }
+        log_msg "Option $key was not present in ODL, inserting one"
+        sed -i "/object 'Configuration' {/,/^ *}/{/^ *}/i\\$param_line }" "$file"
+    fi
+}
+
+# Function: __update_config_option__
+#
+# Updates configuration option in Agent DM
+#
+# Usage: __update_config_option__ <key> <value>
+__update_config_option__() {
+    local key="$1"
+    local value="$2"
+
+    if __dm_obj_exists__ "X_PRPLWARE-COM_Agent.Configuration"; then
+        log_msg "Agent is running: update value of '$key' to '$value' in DM"
+        ba-cli "X_PRPLWARE-COM_Agent.Configuration.$key=$value"
+    elif [ -f "${AGENT_DM_CACHE_FILE_PATH}" ]; then
+        log_msg "Cache file exists: update value of '$key' to '$value'"
+        __sed_config_option_in_odl__ $key $value $AGENT_DM_CACHE_FILE_PATH
+    else
+        log_msg "First run of prplmesh: update value of '$key' to '$value' in defaults.d"
+        __sed_config_option_in_odl__ $key $value $AGENT_DM_DEFAULTS_FILE_PATH
+    fi
+}
+
+__set_repeater_mode__() {
+    __update_config_option__ "ManagementMode" "Agent"
+}
+
+__set_gateway_mode__() {
+    __update_config_option__ "ManagementMode" "Controller+Agent"
+}
+
+__set_certification_mode__() {
+    __update_config_option__ "CertificationMode" "1"
+}
+
+#############################
+# 3. Main Service Operations
+#############################
+
+__start__() {
+    log_msg "Start prplMesh"
+
+    # Waiting for all WLAN ifaces to become ready
+    __wait_for_all_wlan_ready__ || {
+        log_msg "Timeout waiting for WLAN ready!"
+        exit 1
+    }
+
+    # Read ManagementMode from DM, cache, or defaults
+    local management_mode
+    management_mode="$(__get_management_mode__)"
+    log_msg "ManagementMode: ${management_mode}"
+
+    case "$management_mode" in
+    "Controller+Agent")
+        log_msg "Start prplMesh controller & agent"
+        /opt/prplmesh/scripts/prplmesh_utils.sh start -m CA
+        ;;
+    "Agent")
+        log_msg "Start prplMesh agent"
+        /opt/prplmesh/scripts/prplmesh_utils.sh start -m A
+        ;;
+    *)
+        log_msg "Unknown ManagementMode: ${management_mode}, just doing start"
+        /opt/prplmesh/scripts/prplmesh_utils.sh start
+        ;;
+    esac
+}
+
+__stop__() {
+    log_msg "Stop prplMesh"
+
+    /opt/prplmesh/scripts/prplmesh_utils.sh stop
+
+    # since prplmesh changes the wifi runtime configuration,
+    # restart wifi when stopping prplmesh
+    # unless using prplmesh wireless hardware manager
+    ba-cli Device.WiFi.Radio.?0 &>/dev/null || __wlan_reset__
+}
+
+__restart__() {
+    log_msg "Restart prplMesh"
+
+    # prplmesh_utils do the same for 'restart' option (restart = stop & start),
+    # but does not wait for wlan ifaces to become ready,
+    # so it's needed to do this manually
+    __stop__
+    __start__
+}
+
+__status__() {
+    # Show if radios are enabled
+    for radio_name in $(__get_radio_names__); do
+        enabled=$(ba-cli -l "WiFi.Radio.[Name == \"$radio_name\"].Enable?")
+        if [ "$enabled" -eq 1 ]; then
+            echo "$radio_name is enabled"
         else
-                uci set prplmesh.config.wired_backhaul=1
+            echo "$radio_name is disabled"
         fi
-        uci set prplmesh.config.master=0
-        uci set prplmesh.config.gateway=0
-        uci commit prplmesh
+    done
+
+    # prplMesh configuration status
+    __all_wlan_ready__ && echo "WLAN Ready" || echo "WLAN not ready"
+    /opt/prplmesh/scripts/prplmesh_utils.sh status
 }
 
-repeater_mode() {
-        stop
-        __uci_set_repeater_mode__ $1
-        start
-        echo "prplmesh repeater mode set"
+__repeater_mode__() {
+    __set_repeater_mode__
+    __restart__
+    log_msg "prplmesh repeater mode set"
 }
 
-__uci_set_gateway_mode__() {
-        uci commit network
-        uci set prplmesh.config.management_mode='Multi-AP-Controller-and-Agent'
-        uci set prplmesh.config.operating_mode='Gateway'
-        uci set prplmesh.config.wired_backhaul=0
-        uci set prplmesh.config.master=1
-        uci set prplmesh.config.gateway=1
-        uci commit prplmesh
+__gateway_mode__() {
+    __set_gateway_mode__
+    __restart__
+    log_msg "prplmesh gateway mode set"
 }
 
-gateway_mode() {
-        stop
+__certification_mode__() {
+    mode=${1-gateway} # gateway by default
+
+    case "$mode" in
+    controller | gateway | controller_mode | gateway_mode)
         __uci_set_gateway_mode__
-        start
-        echo "prplmesh gateway mode set"
+        __uci_set_certification_mode__
+        ;;
+    agent | repeater | agent_mode | repeater_mode)
+        __uci_set_repeater_mode__
+        __uci_set_certification_mode__
+        ;;
+    esac
+    __restart__
 }
 
-__uci_set_certification_mode__() {
-        uci set prplmesh.config.certification_mode=1
-        uci commit prplmesh
-}
+##################
+# 3. Entry Points
+##################
 
-certification_mode() {
-        mode=${1-controller}
+start() { __start__; }
+stop() { __stop__; }
+restart() { __restart__; }
+status() { __status__; }
+repeater_mode() { __repeater_mode__; }
+gateway_mode() { __gateway_mode__; }
+certification_mode() { __certification_mode__; }
 
-        stop
-        case "$mode" in
-        controller | gateway)
-                __uci_set_gateway_mode__
-                __uci_set_certification_mode__
-                ;;
-        agent | repeater)
-                __uci_set_repeater_mode__
-                __uci_set_certification_mode__
-                ;;
-        esac
-        start
-}
+#############################
+# 4. Extra Commands and Help
+##############################
 
 EXTRA_COMMANDS="status repeater_mode gateway_mode certification_mode"
 EXTRA_HELP='''
